/*
 * tap2go_event.h
 *
 *  Created on: 2018Äê11ÔÂ21ÈÕ
 *      Author: ggg
 */

#ifndef ESL_TAP2GO_EVENT_H_
#define ESL_TAP2GO_EVENT_H_

#define T2G_ACK_LEN			26
#define FRAME1_TIMEOUT      (20)       //50ms

typedef enum T2G_eventHandle{
    T2G_ENT_FINISH,
    T2G_ENT_INIT,
    T2G_ENT_HANDSHAKE_CONFIG,
    T2G_ENT_SEND_COMPLETE,
    T2G_ENT_SEND_HANDSHAKE_HANDLE,

    T2G_ENT_RECV_FRAME1_CONFIG,
    T2G_ENT_RECV_FRAME1_COMPLETE,
    T2G_ENT_RECV_FRAME1_HANDLE,

    T2G_ENT_RECV_DATA_CONFIG,
    T2G_ENT_RECV_DATA_COMPLETE,
    T2G_ENT_RECV_DATA_HANDLE,
    T2G_ENT_RECV_QUERY_HANDLE,
	UPLINK_ENT_RECV_DATA_HANDLE,
    T2G_ENT_RECV_END_PACKET_HANDLE,
    T2G_ENT_SEND_RESPONSE_CONFIG,
    T2G_ENT_SEND_RESPONSE_HANDLE,

    T2G_ENT_ERR_HANDLE,
    T2G_ENT_NUM,
} T2G_eventHandle;

#endif /* ESL_TAP2GO_EVENT_H_ */
